name: Publish Site

on:
  #push:
  #  branches-ignore:
  #    - '**'  
  push:
    branches: [ main ]
  #pull_request:
  # branches: [ main ]
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Requirements
      run: pip3 install sphinx==4.0.3
        && pip3 install sphinx-rtd-theme
        && pip3 install sphinx-sitemap
    - name: Checkout repo
      uses: actions/checkout@1.0.0    
    - name: Build docs
      working-directory: ${{github.workspace}}
      shell: bash
      run: make html
        && cd build
        && touch .nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: ${{github.workspace}}/build/html # The folder the action should deploy.